import { dmSans } from './fonts/dmSans'
import "./global.css";
import "maplibre-gl/dist/maplibre-gl.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={dmSans.variable}>
			<body>{children}</body>
		</html>
	)
}